# 1. Puerto del servidor
server.port=8080

# 2. CONFIGURACION FTP (DOCKER)
ftp.server=127.0.0.1
ftp.port=21
ftp.username=myuser
ftp.password=mypass

# 3. CONFIGURACION GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# AQUI PONGO MI USUARIO Y CONTRASEÑA DE GMAIL PARA ENVIAR LOS CORREOS DESDE LA APLICACION
spring.mail.username=psp.dam2.villacis.ignacio@gmail.com
spring.mail.password=agwe yemp zcyw ntjg